export const categories = [
  { code: 'CT0000001', createdById: 1, nameEn: 'Anti-Mosquito', nameKh: 'ថ្នាំបង្ការមូស' },
  { code: 'CT0000002', createdById: 1, nameEn: 'Armpit Care', nameKh: 'ផលិតផលថែរក្សាក្លៀក' },
  { code: 'CT0000003', createdById: 1, nameEn: 'Baby Care', nameKh: 'ផលិតផលថែរក្សាទារក' },
  { code: 'CT0000004', createdById: 1, nameEn: 'Baby Wash', nameKh: 'សាប៊ូលាងខ្លួនសម្រាប់ទារក' },
  { code: 'CT0000005', createdById: 1, nameEn: 'Balm & Medicated Oil', nameKh: 'ប្រេងបំពង់ និងប្រេងឱសថ' },
  { code: 'CT0000006', createdById: 1, nameEn: 'Body Lotion', nameKh: 'ឡេបំប៉នស្បែក' },
  { code: 'CT0000007', createdById: 1, nameEn: 'Condom & Lubricant', nameKh: 'ស្រោមអនាម័យ និងជែលរំអិល' },
  { code: 'CT0000008', createdById: 1, nameEn: 'Cotton Pads and Buds', nameKh: 'បន្ទះកប្បាស និងឈើសម្អាតត្រចៀក' },
  { code: 'CT0000009', createdById: 1, nameEn: 'Face Cleanser', nameKh: 'សាប៊ូលាងមុខ' },
  { code: 'CT0000010', createdById: 1, nameEn: 'First Aid', nameKh: 'ឧបករណ៍សង្គ្រោះបឋម' },
  { code: 'CT0000011', createdById: 1, nameEn: 'Hair Care', nameKh: 'ផលិតផលថែរក្សាសក់' },
  { code: 'CT0000012', createdById: 1, nameEn: 'Hygiene Product', nameKh: 'ផលិតផលអនាម័យ' },
  { code: 'CT0000013', createdById: 1, nameEn: 'Lip Stick', nameKh: 'លាបបបូរមាត់' },
  { code: 'CT0000014', createdById: 1, nameEn: 'Lozenge', nameKh: 'ថ្នាំបៀមបំពង់ក' },
  { code: 'CT0000015', createdById: 1, nameEn: 'Medical Device', nameKh: 'ឧបករណ៍វេជ្ជសាស្ត្រ' },
  { code: 'CT0000016', createdById: 1, nameEn: 'Men Care', nameKh: 'ផលិតផលថែរក្សាបុរស' },
  { code: 'CT0000017', createdById: 1, nameEn: 'Mouth Care', nameKh: 'ផលិតផលថែរក្សាមាត់ និងធ្មេញ' },
  { code: 'CT0000018', createdById: 1, nameEn: 'Other', nameKh: 'ផ្សេងៗ' },
  { code: 'CT0000019', createdById: 1, nameEn: 'Plaster & Patch', nameKh: 'បង់របួស និងបន្ទះបិត' },
  { code: 'CT0000020', createdById: 1, nameEn: 'Scrub', nameKh: 'ស្រាប់សម្អាតស្បែក' },
  { code: 'CT0000021', createdById: 1, nameEn: 'Skin Care', nameKh: 'ផលិតផលថែរក្សាស្បែក' },
  { code: 'CT0000022', createdById: 1, nameEn: 'Soap & Hand Sanitizer', nameKh: 'សាប៊ូ និងជែលសម្អាតដៃ' },
  { code: 'CT0000023', createdById: 1, nameEn: 'Supplement', nameKh: 'អាហារបំប៉ន' },
  { code: 'CT0000024', createdById: 1, nameEn: 'Supplement For Adult', nameKh: 'អាហារបំប៉នសម្រាប់មនុស្សពេញវ័យ' },
  { code: 'CT0000025', createdById: 1, nameEn: 'Supplement For Kid', nameKh: 'អាហារបំប៉នសម្រាប់កុមារ' },
  { code: 'CT0000026', createdById: 1, nameEn: 'Vitamin Candy & Gummy', nameKh: 'វីតាមីនស្ករគ្រាប់ និងហ្គមមី' },
  { code: 'CT0000027', createdById: 1, nameEn: 'Women Care', nameKh: 'ផលិតផលថែរក្សាស្ត្រី' },
];
