export const users = [
  { username: 'Admin', password: '123', isAdmin: true, isActive: true },

  { username: 'User01', password: '123', isAdmin: false, isActive: true },
  { username: 'User02', password: '123', isAdmin: null, isActive: true },
  { username: 'User03', password: '123', isAdmin: false, isActive: true },
  { username: 'User04', password: '123', isAdmin: false, isActive: true },
  { username: 'User05', password: '123', isAdmin: null, isActive: true },

  { username: 'User06', password: '123', isAdmin: false, isActive: true },
  { username: 'User07', password: '123', isAdmin: false, isActive: true },
  { username: 'User08', password: '123', isAdmin: null, isActive: true },
  { username: 'User09', password: '123', isAdmin: false, isActive: true },
  { username: 'User10', password: '123', isAdmin: false, isActive: true },

  { username: 'User11', password: '123', isAdmin: null, isActive: true },
  { username: 'User12', password: '123', isAdmin: false, isActive: true },
  { username: 'User13', password: '123', isAdmin: false, isActive: true },
  { username: 'User14', password: '123', isAdmin: null, isActive: true },
  { username: 'User15', password: '123', isAdmin: false, isActive: true },

  { username: 'User16', password: '123', isAdmin: false, isActive: true },
  { username: 'User17', password: '123', isAdmin: null, isActive: true },
  { username: 'User18', password: '123', isAdmin: false, isActive: true },
  { username: 'User19', password: '123', isAdmin: false, isActive: true },
  { username: 'User20', password: '123', isAdmin: null, isActive: true },

  { username: 'User21', password: '123', isAdmin: false, isActive: true },
  { username: 'User22', password: '123', isAdmin: false, isActive: true },
  { username: 'User23', password: '123', isAdmin: null, isActive: true },
  { username: 'User24', password: '123', isAdmin: false, isActive: true },
  { username: 'User25', password: '123', isAdmin: false, isActive: true },

  { username: 'User26', password: '123', isAdmin: null, isActive: true },
  { username: 'User27', password: '123', isAdmin: false, isActive: true },
  { username: 'User28', password: '123', isAdmin: false, isActive: true },
  { username: 'User29', password: '123', isAdmin: null, isActive: true },
  { username: 'User30', password: '123', isAdmin: false, isActive: true },

  { username: 'User31', password: '123', isAdmin: false, isActive: true },
  { username: 'User32', password: '123', isAdmin: null, isActive: true },
  { username: 'User33', password: '123', isAdmin: false, isActive: true },
  { username: 'User34', password: '123', isAdmin: false, isActive: true },
  { username: 'User35', password: '123', isAdmin: null, isActive: true },

  { username: 'User36', password: '123', isAdmin: false, isActive: true },
  { username: 'User37', password: '123', isAdmin: false, isActive: true },
  { username: 'User38', password: '123', isAdmin: null, isActive: true },
  { username: 'User39', password: '123', isAdmin: false, isActive: true },
  { username: 'User40', password: '123', isAdmin: false, isActive: true },

  { username: 'User41', password: '123', isAdmin: null, isActive: true },
  { username: 'User42', password: '123', isAdmin: false, isActive: true },
  { username: 'User43', password: '123', isAdmin: false, isActive: true },
  { username: 'User44', password: '123', isAdmin: null, isActive: true },
  { username: 'User45', password: '123', isAdmin: false, isActive: true },

  { username: 'User46', password: '123', isAdmin: false, isActive: true },
  { username: 'User47', password: '123', isAdmin: null, isActive: true },
  { username: 'User48', password: '123', isAdmin: false, isActive: true },
  { username: 'User49', password: '123', isAdmin: false, isActive: true },
  { username: 'User50', password: '123', isAdmin: null, isActive: true },

  { username: 'User51', password: '123', isAdmin: false, isActive: true },
  { username: 'User52', password: '123', isAdmin: false, isActive: true },
  { username: 'User53', password: '123', isAdmin: null, isActive: true },
  { username: 'User54', password: '123', isAdmin: false, isActive: true },
  { username: 'User55', password: '123', isAdmin: false, isActive: true },

  { username: 'User56', password: '123', isAdmin: null, isActive: true },
  { username: 'User57', password: '123', isAdmin: false, isActive: true },
  { username: 'User58', password: '123', isAdmin: false, isActive: true },
  { username: 'User59', password: '123', isAdmin: null, isActive: true },
  { username: 'User60', password: '123', isAdmin: false, isActive: true },

  { username: 'User61', password: '123', isAdmin: false, isActive: true },
  { username: 'User62', password: '123', isAdmin: null, isActive: true },
  { username: 'User63', password: '123', isAdmin: false, isActive: true },
  { username: 'User64', password: '123', isAdmin: false, isActive: true },
  { username: 'User65', password: '123', isAdmin: null, isActive: true },

  { username: 'User66', password: '123', isAdmin: false, isActive: true },
  { username: 'User67', password: '123', isAdmin: false, isActive: true },
  { username: 'User68', password: '123', isAdmin: null, isActive: true },
  { username: 'User69', password: '123', isAdmin: false, isActive: true },
  { username: 'User70', password: '123', isAdmin: false, isActive: true },

  { username: 'User71', password: '123', isAdmin: null, isActive: true },
  { username: 'User72', password: '123', isAdmin: false, isActive: true },
  { username: 'User73', password: '123', isAdmin: false, isActive: true },
  { username: 'User74', password: '123', isAdmin: null, isActive: true },
  { username: 'User75', password: '123', isAdmin: false, isActive: true },

  { username: 'User76', password: '123', isAdmin: false, isActive: true },
  { username: 'User77', password: '123', isAdmin: null, isActive: true },
  { username: 'User78', password: '123', isAdmin: false, isActive: true },
  { username: 'User79', password: '123', isAdmin: false, isActive: true },
  { username: 'User80', password: '123', isAdmin: null, isActive: true },

  { username: 'User81', password: '123', isAdmin: false, isActive: true },
  { username: 'User82', password: '123', isAdmin: false, isActive: true },
  { username: 'User83', password: '123', isAdmin: null, isActive: true },
  { username: 'User84', password: '123', isAdmin: false, isActive: true },
  { username: 'User85', password: '123', isAdmin: false, isActive: true },

  { username: 'User86', password: '123', isAdmin: null, isActive: true },
  { username: 'User87', password: '123', isAdmin: false, isActive: true },
  { username: 'User88', password: '123', isAdmin: false, isActive: true },
  { username: 'User89', password: '123', isAdmin: null, isActive: true },
  { username: 'User90', password: '123', isAdmin: false, isActive: true },

  { username: 'User91', password: '123', isAdmin: false, isActive: true },
  { username: 'User92', password: '123', isAdmin: null, isActive: true },
  { username: 'User93', password: '123', isAdmin: false, isActive: true },
  { username: 'User94', password: '123', isAdmin: false, isActive: true },
  { username: 'User95', password: '123', isAdmin: null, isActive: true },

  { username: 'User96', password: '123', isAdmin: false, isActive: true },
  { username: 'User97', password: '123', isAdmin: false, isActive: true },
  { username: 'User98', password: '123', isAdmin: null, isActive: true },
  { username: 'User99', password: '123', isAdmin: false, isActive: true },
  { username: 'User100', password: '123', isAdmin: false, isActive: true },
]
